// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/health/domain/health_event.dart';
import 'features/health/domain/weight_record.dart';
import 'features/journal/domain/journal_entry.dart';
import 'features/journal/domain/media_item.dart';
import 'features/pets/domain/pet.dart';
import 'features/reminders/domain/reminder.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7149612474107203587),
    name: 'HealthEvent',
    lastPropertyId: const obx_int.IdUid(7, 1223480558354048311),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1189483817150987838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3762683671183320166),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 2105403124516911973),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8601280197126941343),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2872764105780604392),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1279093268846239201),
        name: 'eventAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2274427786673579380),
        name: 'nextAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1223480558354048311),
        name: 'typeValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6839449204823800348),
    name: 'JournalEntry',
    lastPropertyId: const obx_int.IdUid(7, 433070239170055169),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 602162287806208266),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1921811077989809785),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 8401091193762552123),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 641446887186504986),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4059767839113985991),
        name: 'mood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 70941230653440367),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4415166465987928765),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 433070239170055169),
        name: 'entryAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1211371668084566910),
    name: 'MediaItem',
    lastPropertyId: const obx_int.IdUid(5, 43815013671811982),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2479829178354947866),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7740305284256258502),
        name: 'entryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4888852344970640727),
        relationField: 'entry',
        relationTarget: 'JournalEntry',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8692734692991623869),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3186318354172080978),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 43815013671811982),
        name: 'typeValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3783277932914995685),
    name: 'Pet',
    lastPropertyId: const obx_int.IdUid(8, 438959370123947486),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5173272140031998367),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1452771560361489801),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4257605897201166995),
        name: 'species',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5868722497239028996),
        name: 'breed',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6074588296232660867),
        name: 'birthDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4721349552183633825),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3999384723495582208),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 438959370123947486),
        name: 'sexValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7912505800039096629),
    name: 'Reminder',
    lastPropertyId: const obx_int.IdUid(8, 417858815798101858),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 922175126336626385),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9092261702951908787),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 6171320217010874837),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3701712679219478305),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2084060280203340486),
        name: 'scheduledAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7464326231828129942),
        name: 'repeatRule',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4374020551036728158),
        name: 'isEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1429966927901895831),
        name: 'relatedEventId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 417858815798101858),
        name: 'typeValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7556152409372253130),
    name: 'WeightRecord',
    lastPropertyId: const obx_int.IdUid(4, 3653625695122590826),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8454074806944496858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3511507783066037334),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 133486031347927233),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2337470381093989052),
        name: 'weight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3653625695122590826),
        name: 'recordedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 7556152409372253130),
    lastIndexId: const obx_int.IdUid(5, 133486031347927233),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HealthEvent: obx_int.EntityDefinition<HealthEvent>(
      model: _entities[0],
      toOneRelations: (HealthEvent object) => [object.pet],
      toManyRelations: (HealthEvent object) => {},
      getId: (HealthEvent object) => object.id,
      setId: (HealthEvent object, int id) {
        object.id = id;
      },
      objectToFB: (HealthEvent object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pet.targetId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, notesOffset);
        fbb.addInt64(4, object.eventAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.nextAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.typeValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nextAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final typeValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final eventAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final nextAtParam = nextAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(nextAtValue);
        final object = HealthEvent(
          typeValue: typeValueParam,
          title: titleParam,
          notes: notesParam,
          eventAt: eventAtParam,
          nextAt: nextAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
    JournalEntry: obx_int.EntityDefinition<JournalEntry>(
      model: _entities[1],
      toOneRelations: (JournalEntry object) => [object.pet],
      toManyRelations: (JournalEntry object) => {},
      getId: (JournalEntry object) => object.id,
      setId: (JournalEntry object, int id) {
        object.id = id;
      },
      objectToFB: (JournalEntry object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final moodOffset = object.mood == null
            ? null
            : fbb.writeString(object.mood!);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pet.targetId);
        fbb.addOffset(2, textOffset);
        fbb.addOffset(3, moodOffset);
        fbb.addOffset(4, tagsOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.entryAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final moodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final entryAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = JournalEntry(
          text: textParam,
          tags: tagsParam,
          mood: moodParam,
          createdAt: createdAtParam,
          entryAt: entryAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
    MediaItem: obx_int.EntityDefinition<MediaItem>(
      model: _entities[2],
      toOneRelations: (MediaItem object) => [object.entry],
      toManyRelations: (MediaItem object) => {},
      getId: (MediaItem object) => object.id,
      setId: (MediaItem object, int id) {
        object.id = id;
      },
      objectToFB: (MediaItem object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.entry.targetId);
        fbb.addOffset(2, pathOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.typeValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final typeValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = MediaItem(
          typeValue: typeValueParam,
          path: pathParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.entry.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.entry.attach(store);
        return object;
      },
    ),
    Pet: obx_int.EntityDefinition<Pet>(
      model: _entities[3],
      toOneRelations: (Pet object) => [],
      toManyRelations: (Pet object) => {},
      getId: (Pet object) => object.id,
      setId: (Pet object, int id) {
        object.id = id;
      },
      objectToFB: (Pet object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final speciesOffset = fbb.writeString(object.species);
        final breedOffset = object.breed == null
            ? null
            : fbb.writeString(object.breed!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, speciesOffset);
        fbb.addOffset(3, breedOffset);
        fbb.addInt64(4, object.birthDate?.millisecondsSinceEpoch);
        fbb.addOffset(5, photoPathOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.sexValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final birthDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final speciesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final breedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final birthDateParam = birthDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(birthDateValue);
        final sexValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = Pet(
          name: nameParam,
          species: speciesParam,
          breed: breedParam,
          birthDate: birthDateParam,
          sexValue: sexValueParam,
          photoPath: photoPathParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Reminder: obx_int.EntityDefinition<Reminder>(
      model: _entities[4],
      toOneRelations: (Reminder object) => [object.pet],
      toManyRelations: (Reminder object) => {},
      getId: (Reminder object) => object.id,
      setId: (Reminder object, int id) {
        object.id = id;
      },
      objectToFB: (Reminder object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final repeatRuleOffset = object.repeatRule == null
            ? null
            : fbb.writeString(object.repeatRule!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pet.targetId);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.scheduledAt.millisecondsSinceEpoch);
        fbb.addOffset(4, repeatRuleOffset);
        fbb.addBool(5, object.isEnabled);
        fbb.addInt64(6, object.relatedEventId);
        fbb.addInt64(7, object.typeValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final typeValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scheduledAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final repeatRuleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final isEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final relatedEventIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = Reminder(
          typeValue: typeValueParam,
          title: titleParam,
          scheduledAt: scheduledAtParam,
          repeatRule: repeatRuleParam,
          isEnabled: isEnabledParam,
          relatedEventId: relatedEventIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
    WeightRecord: obx_int.EntityDefinition<WeightRecord>(
      model: _entities[5],
      toOneRelations: (WeightRecord object) => [object.pet],
      toManyRelations: (WeightRecord object) => {},
      getId: (WeightRecord object) => object.id,
      setId: (WeightRecord object, int id) {
        object.id = id;
      },
      objectToFB: (WeightRecord object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pet.targetId);
        fbb.addFloat64(2, object.weight);
        fbb.addInt64(3, object.recordedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final weightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final recordedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = WeightRecord(
          weight: weightParam,
          recordedAt: recordedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HealthEvent] entity fields to define ObjectBox queries.
class HealthEvent_ {
  /// See [HealthEvent.id].
  static final id = obx.QueryIntegerProperty<HealthEvent>(
    _entities[0].properties[0],
  );

  /// See [HealthEvent.pet].
  static final pet = obx.QueryRelationToOne<HealthEvent, Pet>(
    _entities[0].properties[1],
  );

  /// See [HealthEvent.title].
  static final title = obx.QueryStringProperty<HealthEvent>(
    _entities[0].properties[2],
  );

  /// See [HealthEvent.notes].
  static final notes = obx.QueryStringProperty<HealthEvent>(
    _entities[0].properties[3],
  );

  /// See [HealthEvent.eventAt].
  static final eventAt = obx.QueryDateProperty<HealthEvent>(
    _entities[0].properties[4],
  );

  /// See [HealthEvent.nextAt].
  static final nextAt = obx.QueryDateProperty<HealthEvent>(
    _entities[0].properties[5],
  );

  /// See [HealthEvent.typeValue].
  static final typeValue = obx.QueryIntegerProperty<HealthEvent>(
    _entities[0].properties[6],
  );
}

/// [JournalEntry] entity fields to define ObjectBox queries.
class JournalEntry_ {
  /// See [JournalEntry.id].
  static final id = obx.QueryIntegerProperty<JournalEntry>(
    _entities[1].properties[0],
  );

  /// See [JournalEntry.pet].
  static final pet = obx.QueryRelationToOne<JournalEntry, Pet>(
    _entities[1].properties[1],
  );

  /// See [JournalEntry.text].
  static final text = obx.QueryStringProperty<JournalEntry>(
    _entities[1].properties[2],
  );

  /// See [JournalEntry.mood].
  static final mood = obx.QueryStringProperty<JournalEntry>(
    _entities[1].properties[3],
  );

  /// See [JournalEntry.tags].
  static final tags = obx.QueryStringVectorProperty<JournalEntry>(
    _entities[1].properties[4],
  );

  /// See [JournalEntry.createdAt].
  static final createdAt = obx.QueryDateProperty<JournalEntry>(
    _entities[1].properties[5],
  );

  /// See [JournalEntry.entryAt].
  static final entryAt = obx.QueryDateProperty<JournalEntry>(
    _entities[1].properties[6],
  );
}

/// [MediaItem] entity fields to define ObjectBox queries.
class MediaItem_ {
  /// See [MediaItem.id].
  static final id = obx.QueryIntegerProperty<MediaItem>(
    _entities[2].properties[0],
  );

  /// See [MediaItem.entry].
  static final entry = obx.QueryRelationToOne<MediaItem, JournalEntry>(
    _entities[2].properties[1],
  );

  /// See [MediaItem.path].
  static final path = obx.QueryStringProperty<MediaItem>(
    _entities[2].properties[2],
  );

  /// See [MediaItem.createdAt].
  static final createdAt = obx.QueryDateProperty<MediaItem>(
    _entities[2].properties[3],
  );

  /// See [MediaItem.typeValue].
  static final typeValue = obx.QueryIntegerProperty<MediaItem>(
    _entities[2].properties[4],
  );
}

/// [Pet] entity fields to define ObjectBox queries.
class Pet_ {
  /// See [Pet.id].
  static final id = obx.QueryIntegerProperty<Pet>(_entities[3].properties[0]);

  /// See [Pet.name].
  static final name = obx.QueryStringProperty<Pet>(_entities[3].properties[1]);

  /// See [Pet.species].
  static final species = obx.QueryStringProperty<Pet>(
    _entities[3].properties[2],
  );

  /// See [Pet.breed].
  static final breed = obx.QueryStringProperty<Pet>(_entities[3].properties[3]);

  /// See [Pet.birthDate].
  static final birthDate = obx.QueryDateProperty<Pet>(
    _entities[3].properties[4],
  );

  /// See [Pet.photoPath].
  static final photoPath = obx.QueryStringProperty<Pet>(
    _entities[3].properties[5],
  );

  /// See [Pet.createdAt].
  static final createdAt = obx.QueryDateProperty<Pet>(
    _entities[3].properties[6],
  );

  /// See [Pet.sexValue].
  static final sexValue = obx.QueryIntegerProperty<Pet>(
    _entities[3].properties[7],
  );
}

/// [Reminder] entity fields to define ObjectBox queries.
class Reminder_ {
  /// See [Reminder.id].
  static final id = obx.QueryIntegerProperty<Reminder>(
    _entities[4].properties[0],
  );

  /// See [Reminder.pet].
  static final pet = obx.QueryRelationToOne<Reminder, Pet>(
    _entities[4].properties[1],
  );

  /// See [Reminder.title].
  static final title = obx.QueryStringProperty<Reminder>(
    _entities[4].properties[2],
  );

  /// See [Reminder.scheduledAt].
  static final scheduledAt = obx.QueryDateProperty<Reminder>(
    _entities[4].properties[3],
  );

  /// See [Reminder.repeatRule].
  static final repeatRule = obx.QueryStringProperty<Reminder>(
    _entities[4].properties[4],
  );

  /// See [Reminder.isEnabled].
  static final isEnabled = obx.QueryBooleanProperty<Reminder>(
    _entities[4].properties[5],
  );

  /// See [Reminder.relatedEventId].
  static final relatedEventId = obx.QueryIntegerProperty<Reminder>(
    _entities[4].properties[6],
  );

  /// See [Reminder.typeValue].
  static final typeValue = obx.QueryIntegerProperty<Reminder>(
    _entities[4].properties[7],
  );
}

/// [WeightRecord] entity fields to define ObjectBox queries.
class WeightRecord_ {
  /// See [WeightRecord.id].
  static final id = obx.QueryIntegerProperty<WeightRecord>(
    _entities[5].properties[0],
  );

  /// See [WeightRecord.pet].
  static final pet = obx.QueryRelationToOne<WeightRecord, Pet>(
    _entities[5].properties[1],
  );

  /// See [WeightRecord.weight].
  static final weight = obx.QueryDoubleProperty<WeightRecord>(
    _entities[5].properties[2],
  );

  /// See [WeightRecord.recordedAt].
  static final recordedAt = obx.QueryDateProperty<WeightRecord>(
    _entities[5].properties[3],
  );
}
